module Telemetry {

    typedef string<256> SpanId;
    typedef string<256> TraceId;
    typedef int64 Timestamp;

    @appendable
    struct Span {
        @key SpanId span_id;
        TraceId trace_id;
        string<256> name;
        Timestamp start_time;
        Timestamp end_time;
        sequence<string<256>> attributes;
        @optional sequence<Span> nested_spans;
    };

    @appendable
    struct TelemetryData {
        @key string<256> source;
        sequence<Span> spans;
    };
};